In [22]:
# Carregando os dados do arquivo CSV.
# https://www.kaggle.com/dell4010/wine-dataset

import pandas as pd
arquivo = pd.read_csv('/Users/knox/wine_dataset.csv')

In [23]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [24]:
# Subistituindo os valores string por numericos na coluna style

arquivo['style'] = arquivo['style'].replace('red',0)
arquivo['style'] = arquivo['style'].replace('white',1)

In [25]:
# Verificando o arquivo após a substituiçao na coluna style
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [26]:
# Separando as variáveis em preditoras e alvo, onde alvo é a variável que se quer prever, neste caso style

y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [36]:
# separando 30% do conjunto de dados para testes, e 70% para treino
# a função train_test_split já nos da 4 saida

from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [44]:
from sklearn.ensemble import ExtraTreesClassifier

# Criação do modelo, para rodar no algorítimo de machine learne "ExtraTreesClassifier"
# função fit utilizada para aplicar o algotítmo "ExtraTreesClassifier" aos dados de treino previamente selecionados

modelo = ExtraTreesClassifier(n_estimators=100)
modelo.fit(x_treino,y_treino)

resultado = modelo.score(x_teste, y_teste)
print("Taxa de acerto: ", resultado)

Taxa de acerto:  0.9964102564102564

In [50]:
# Filtrando 10 amostras aleatoriamente do conjunto de teste. abaixo os respectivos valores para a coluna style.
# O objetivo é fazer com que o altorítimo agora que treinado consiga predizer o resultado ou seja, ele recebera 
# as 10 amostras e determinará o tipo de vinho, através do modo predict, e poderemos validar através do Out[51]

x_teste[400:410]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2887,7.2,0.32,0.33,1.40,0.029,29.0,109.0,0.99020,3.15,0.51,12.8,7
1541,7.4,0.25,0.29,2.20,0.054,19.0,49.0,0.99666,3.40,0.76,10.9,7
3364,6.9,0.29,0.23,8.60,0.056,56.0,215.0,0.99670,3.17,0.44,8.8,5
1006,9.1,0.29,0.33,2.05,0.063,13.0,27.0,0.99516,3.26,0.84,11.7,7
1961,6.8,0.15,0.30,5.30,0.050,40.0,127.0,0.99420,3.40,0.39,9.7,6
300,7.5,0.53,0.06,2.60,0.086,20.0,44.0,0.99650,3.38,0.59,10.7,6
1966,6.9,0.33,0.21,1.00,0.053,39.0,148.0,0.99270,3.12,0.45,9.4,6
1543,11.1,0.44,0.42,2.20,0.064,14.0,19.0,0.99758,3.25,0.57,10.4,6
5648,6.8,0.16,0.36,1.30,0.034,32.0,98.0,0.99058,3.02,0.58,11.3,6
5830,7.5,0.35,0.37,2.50,0.066,29.0,89.0,0.98964,3.14,0.42,12.7,6

In [51]:
y_teste[400:410]

2887    1
1541    0
3364    1
1006    0
1961    1
300     0
1966    1
1543    0
5648    1
5830    1
Name: style, dtype: int64

In [52]:
previsao = modelo.predict(x_teste[400:410])

In [57]:
previsao

array([1, 1, 0, 1, 1])